name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  dev:
    name: Dev
    runs-on: ubuntu-latest
    steps:
      - name: TBD
        run: echo TBD!
  qa:
    name: QA
    runs-on: ubuntu-latest
    needs: dev
    steps:
      - name: TBD
        run: echo TBD!
  uat:
    name: UAT
    runs-on: ubuntu-latest
    needs: qa
    steps:
      - name: TBD
        run: echo TBD!
  pre-prod:
    name: Preview
    runs-on: ubuntu-latest
    needs:
      - uat
    strategy:
      matrix:
        include:
          - site: "production"
            datacenter: "site-a"
          - site: "staging"
            datacenter: "site-b"
  prod:
    name: Production
    runs-on: ubuntu-latest
    needs: 
      - pre-prod
    steps:
      - name: TBD
        run: echo TBD!