name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  dev:
    name: Dev
    runs-on: ubuntu-latest
    steps:
      - name: Unit Tests
        run: echo Unit Tests Success!
      - name: SAST
        run: echo SAST Success!
      - name: SCA
        run: echo SCA Success!
      - name: IAST
        run: echo IAST Success!
      - name: Security Unit Testing
        run: echo Security Unit Testing Success!
      - name: Initial Threat Modeling
        run: echo Initial Threat Modeling Success!
  qa:
    name: QA
    runs-on: ubuntu-latest
    needs: dev
    steps:
      - name: Integration Tests
        run: echo Integration Tests Success!
      - name: SIT
        run: echo SIT Success!
      - name: DAST
        run: echo DAST Success!
      - name: API Security Testing
        run: echo API Security Testing Success!
      - name: Refine Threat Model
        run: echo Refine Threat Model Success!
  uat:
    name: UAT
    runs-on: ubuntu-latest
    needs: qa
    steps:
      - name: TBD
        run: echo TBD!
  stage:
    name: Stage
    runs-on: ubuntu-latest
    needs: qa
    steps:
      - name: TBD
        run: echo TBD!
  pre-prod:
    name: Pre-Prod
    runs-on: ubuntu-latest
    needs: 
      - uat
      - stage
    steps:
      - name: TBD
        run: echo TBD!
  prod:
    name: Production
    runs-on: ubuntu-latest
    needs: 
      - pre-prod
    steps:
      - name: TBD
        run: echo TBD!