name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  dev:
    name: Dev
    runs-on: ubuntu-latest
    steps:
      - name: Unit Tests
        run: echo Unit Tests Success!
      - name: SAST
        run: echo SAST Success!
      - name: SCA
        run: echo SCA Success!
      - name: IAST
        run: echo IAST Success!
      - name: Security Unit Testing
        run: echo Security Unit Testing Success!
      - name: Initial Threat Modeling
        run: echo Initial Threat Modeling Success!