name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  dev:
    name: Dev
    runs-on: ubuntu-latest
    steps:
      - name: Unit Tests
        run: Unit Tests Success!
      - name: SAST
        run: SAST Success!
      - name: SCA
        run: SCA Success!
      - name: IAST
        run: IAST Success!
      - name: Security Unit Testing
        run: Security Unit Testing Success!
      - name: Initial Threat Modeling
        run: Initial Threat Modeling Success!